apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: dockerconfigjson-ghcr-io
      containers:
      - name: backend
        image: ghcr.io/pokgak/feedme/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: MONGODB_USER
            value: feedme
          - name: MONGODB_PASSWORD
            value: password
          - name: MONGODB_URL
            value: "mongodb://$(MONGODB_USER):$(MONGODB_PASSWORD)@mongo.mongo.svc.cluster.local:27017"
          - name: OTEL_SERVICE_NAME
            value: feedme
          - name: BASELIME_KEY
            valueFrom:
              configMapKeyRef:
                name: feedme-config
                key: BASELIME_KEY
        resources:
          requests:
            cpu: 100m
            memory: 128Mi