---
namespace: monitoring

resources:
  - namespace.yaml

helmCharts:
  - name: grafana
    releaseName: grafana
    repo: https://grafana.github.io/helm-charts
    namespace: monitoring
    version: 7.2.4
